# numpy cheatsheet - array manipulation routines
本文档包含绝大多数numpy操作数组的函数，但不包含ufunc，ufunc文档在另外的notebook中

In [1]:
# 引入numpy和matplotlib内联
import numpy as np
%matplotlib inline

## 总体参数说明
- a/array_like: 可以使用__array__函数返回成数组任何对象，包括```list, tuple, list[list...], tuple[tuple...], list[tuple...], tuple[list...]```
- v: 向量参数
- shape: numpy数组的各维度长度的tuple
- out: 代入的numpy数组作为输出
- dtype: numpy数组类型
- order: C顺序或Fortran顺序
- subok: True返回ndarray的子类，False返回ndarray
- axis: 操作的维度，第一个维度为0，以此类推
- axes：操作维度的集合

## 基本操作

In [2]:
# copyto(dst, src [, casting, where])
# dst - 目标的numpy数组
# src - 源array_like参数
# casting - 'no': 数据类型不做任何转换；'equiv': 仅允许字节顺序的转换；'safe': 仅允许能保留数据值的转换；
#           'same_kind'（默认值）: 仅允许相同数据类型间的转换，如整数到整数；'unsafe': 允许任何转换
# where - 一个boolean的数组，True的元素代表该位置的数据将会被拷贝到目标中
# 将源数组数据拷贝到目标数组中，如果需要的话，广播方式将被采用
python_list = [[1,2,3],[4,5,6],[7,8,9]]
src = np.array(python_list)
dst = np.zeros((3, 3))
np.copyto(dst, src)
print(dst)
dst = np.zeros((3, 3))
np.copyto(dst, src, where=src>5)
print(dst)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 0.  0.  0.]
 [ 0.  0.  6.]
 [ 7.  8.  9.]]


## 改变数组的形状

In [3]:
# reshape(a, shape [, order])
# 将数组改变为shape形状，shape中的所有元素的乘积应该等于a.shape中所有元素的乘积
arr = np.reshape(np.arange(12), (3, 4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
# ravel(a [, order])
# ndarray.flatten([order])
# 将a扁平化后变成一个一维向量数组，ravel尽量返回a的视图，特殊情况下才返回a的拷贝，flatten始终返回a的拷贝
arr = np.ravel(np.arange(12).reshape(3, 4))
print(arr)
arr = np.arange(12).reshape(3, 4).flatten()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
# ndarray.flat
# 数组扁平化后的迭代器
arr = np.arange(12).reshape(3, 4)
print(arr.flat[5])
print(arr.T.flat[5])

5
9


## 矩阵转置类型操作

In [6]:
# moveaxis(a, source, destination)
# source - int或int的tuple，源维度的序号（列表）
# destination - int或int的tuple，目标维度的序号（列表）
# 将数组中的维度移动到目标维度上
arr = np.arange(12).reshape(2, 3, 2)
print(arr)
print(np.moveaxis(arr, 0, 1))
print(np.moveaxis(arr, (0, 1), (1, 2)))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1]
  [ 6  7]]

 [[ 2  3]
  [ 8  9]]

 [[ 4  5]
  [10 11]]]
[[[ 0  2  4]
  [ 6  8 10]]

 [[ 1  3  5]
  [ 7  9 11]]]


In [7]:
# swapaxes(a, axis1, axis2)
# axis1, axis2 - 用于交换位置的两个维度序号
# 将数组a中的两个维度交换位置
arr = np.arange(12).reshape(2, 3, 2)
print(arr)
print(np.swapaxes(arr, 0, 2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [8]:
# transpose(a [, axes])
# 获得数组的置换结果
arr = np.array([[1,2],[3,4]])
print(np.transpose(arr))
arr = np.arange(12).reshape(2, 3, 2)
print(np.transpose(arr, (-1, 1, 0)))

[[1 3]
 [2 4]]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [9]:
# ndarray.T
# 与self.transpose相同，除了当数组是一维时将会返回self自身
arr = np.array([[1,2],[3,4]])
print(arr.T)
arr = np.arange(12).reshape(2, 3, 2)
print(arr.T)

[[1 3]
 [2 4]]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


## 修改数组的维度

In [10]:
# atleast_1d(*arys)
# atleast_2d(*arys)
# atleast_3d(*arys)
# arys - 输入的数据，如果是标量，将会转换为对应1/2/3维数组，如果输入的数组已经满足维度要求，则保留原结构
# 将输入转换为至少一维的numpy数组
arr = np.atleast_1d(1)
print(arr)
arr = np.atleast_1d([[1,2],[3,4]])
print(arr)
arr = np.atleast_1d(1, [2, 3])
print(arr)
arr = np.atleast_2d(1)
print(arr)
arr = np.atleast_2d([[1,2],[3,4]])
print(arr)
arr = np.atleast_2d(1, [2, 3])
print(arr)
arr = np.atleast_3d(1)
print(arr)
arr = np.atleast_3d([[1,2],[3,4]])
print(arr)
arr = np.atleast_3d(1, [2, 3])
print(arr)

[1]
[[1 2]
 [3 4]]
[array([1]), array([2, 3])]
[[1]]
[[1 2]
 [3 4]]
[array([[1]]), array([[2, 3]])]
[[[1]]]
[[[1]
  [2]]

 [[3]
  [4]]]
[array([[[1]]]), array([[[2],
        [3]]])]


In [11]:
# broadcast_to(a, shape [, subok])
# 将a数组以numpy广播方式扩展到shape形状
arr = np.array([1, 2, 3])
print(np.broadcast_to(arr, (3, 3)))
arr = np.arange(12).reshape(2, 3, 2)
print(np.broadcast_to(arr, (3, 2, 3, 2)))

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]]


In [12]:
# broadcast_arrays(*arys [, subok])
# arys - 用于进行广播扩展的数组
# 将输入的多个数组进行广播扩展，返回一个非连续分配空间的视图
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1], [2], [3]])
print(np.broadcast_arrays(arr1, arr2))
arr3 = np.arange(9).reshape(3, 3, 1)
print(np.broadcast_arrays(arr1, arr2, arr3))

[array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]), array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])]
[array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]]), array([[[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]]), array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]],

       [[6, 6, 6],
        [7, 7, 7],
        [8, 8, 8]]])]


In [13]:
# expand_dims(a, axis)
# 为数组a增加一个维度，维度的位置由axis参数设定，通常等同于a[...,np.newaxis,...]操作
arr = np.array([[1,2],[3,4]])
print(np.expand_dims(arr, axis=0))
print(arr[np.newaxis,...])
print(arr[None,...])
print(np.expand_dims(arr, axis=1))
print(arr[:,None,:])

[[[1 2]
  [3 4]]]
[[[1 2]
  [3 4]]]
[[[1 2]
  [3 4]]]
[[[1 2]]

 [[3 4]]]
[[[1 2]]

 [[3 4]]]


In [14]:
# squeeze(a [, axis])
# 减少数组的维度，被减少的维度必须长度为1，可以通过axis参数设置被减少的维度序号（列表）
arr = np.array([[[1],[2],[3]]])
print(np.squeeze(arr))
print(np.squeeze(arr, axis=0))
print(np.squeeze(arr, axis=2))

[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]


## 合并数组

In [15]:
# concatenate((a1, a2, ...) [, axis, out])
# a1, a2, ... - 需要合并的数组sequence，这些数组必须在除axis维度外其他维度形状一致
# 将多个数组合并成一个数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5])
print(np.concatenate((arr1, arr2)))
arr1 = np.arange(12).reshape(2, 3, 2)
arr2 = np.arange(100, 108).reshape(2, 2, 2)
print(np.concatenate((arr1, arr2), axis=1))

[1 2 3 4 5]
[[[  0   1]
  [  2   3]
  [  4   5]
  [100 101]
  [102 103]]

 [[  6   7]
  [  8   9]
  [ 10  11]
  [104 105]
  [106 107]]]


In [16]:
# stack((a1, a2, ...) [, axis, out])
# a1, a2, ... - 需要叠放的数组sequence，这些数组必须具有相同的形状
# 将多个数组叠放在一起，组成一个具有新的维度的数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.stack((arr1, arr2)))
arr1 = np.arange(12).reshape(2, 3, 2)
arr2 = np.arange(100, 112).reshape(2, 3, 2)
print(np.stack((arr1, arr2), axis=-1)) # 新的shape应该是(2, 3, 2, 2)

[[1 2 3]
 [4 5 6]]
[[[[  0 100]
   [  1 101]]

  [[  2 102]
   [  3 103]]

  [[  4 104]
   [  5 105]]]


 [[[  6 106]
   [  7 107]]

  [[  8 108]
   [  9 109]]

  [[ 10 110]
   [ 11 111]]]]


In [17]:
# dstack((a1, a2, ...)) - 将数组叠放在第三维度上
# hstack((a1, a2, ...)) - 将数组叠放在第二维度上，如果数组都是一维向量，则叠放在第一维度上
# vstack((a1, a2, ...)) - 将数组叠放在第一维度上
# 所有的数组除了在要叠放的维度上可以长度不一致外，其他维度必须形状相同
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.dstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))
print(np.vstack((arr1, arr2)))
arr1 = np.arange(12).reshape(2, 3, 2)
arr2 = np.arange(100, 112).reshape(2, 3, 2)
print(np.dstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))
print(np.vstack((arr1, arr2)))

[[[1 4]
  [2 5]
  [3 6]]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[  0   1 100 101]
  [  2   3 102 103]
  [  4   5 104 105]]

 [[  6   7 106 107]
  [  8   9 108 109]
  [ 10  11 110 111]]]
[[[  0   1]
  [  2   3]
  [  4   5]
  [100 101]
  [102 103]
  [104 105]]

 [[  6   7]
  [  8   9]
  [ 10  11]
  [106 107]
  [108 109]
  [110 111]]]
[[[  0   1]
  [  2   3]
  [  4   5]]

 [[  6   7]
  [  8   9]
  [ 10  11]]

 [[100 101]
  [102 103]
  [104 105]]

 [[106 107]
  [108 109]
  [110 111]]]


In [18]:
# block(arys)
# arys - array_like组成的list，表示需要合并的各部分区块
# 使用list定义的区块合并一个新的numpy数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.block([[np.zeros(3), arr1], [arr2, np.zeros(3)]]))

[[ 0.  0.  0.  1.  2.  3.]
 [ 4.  5.  6.  0.  0.  0.]]


## 分割数组

In [19]:
# split(a, indices_or_sections [, axis])
# array_split(a, indices_or_sections [, axis])
# indices_or_sections - sections，该参数为整数，表示数组应该沿axis维度平均分为多少份，
#                                 如果不能平均分割，split会抛出错误，array_split会尽量平均分割
#                       indices, 该参数为一维有序数组，表示数组沿axis维度分割的分割点
arr = np.arange(12).reshape(2, 6)
print(np.split(arr, 3, axis=1))
print(np.split(arr, [1, 3], axis=1))
print(np.array_split(arr.ravel(), 5))

[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
[array([[0],
       [6]]), array([[1, 2],
       [7, 8]]), array([[ 3,  4,  5],
       [ 9, 10, 11]])]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9]), array([10, 11])]


In [20]:
# dsplit(a, indices_or_sections) 将数组沿第三维度分割
# hsplit(a, indices_or_sections) 将数组沿第二维度分割
# vsplit(a, indices_or_sections) 将数组沿第一维度分割
arr = np.arange(36).reshape(2, 3, 6)
print(np.dsplit(arr, 3))
print(np.dsplit(arr, [1, 3]))
print(np.hsplit(arr, 3))
print(np.vsplit(arr, 2))

[array([[[ 0,  1],
        [ 6,  7],
        [12, 13]],

       [[18, 19],
        [24, 25],
        [30, 31]]]), array([[[ 2,  3],
        [ 8,  9],
        [14, 15]],

       [[20, 21],
        [26, 27],
        [32, 33]]]), array([[[ 4,  5],
        [10, 11],
        [16, 17]],

       [[22, 23],
        [28, 29],
        [34, 35]]])]
[array([[[ 0],
        [ 6],
        [12]],

       [[18],
        [24],
        [30]]]), array([[[ 1,  2],
        [ 7,  8],
        [13, 14]],

       [[19, 20],
        [25, 26],
        [31, 32]]]), array([[[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]],

       [[21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]]])]
[array([[[ 0,  1,  2,  3,  4,  5]],

       [[18, 19, 20, 21, 22, 23]]]), array([[[ 6,  7,  8,  9, 10, 11]],

       [[24, 25, 26, 27, 28, 29]]]), array([[[12, 13, 14, 15, 16, 17]],

       [[30, 31, 32, 33, 34, 35]]])]
[array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17

## 重复铺放数组

In [21]:
# tile(a, reps)
# repeat(a, reps [, axis])
# reps - 重复次数
# tile重复放置reps次a数组形成一个新数组；repeat重复a数组中沿axis维度的元素reps次形成新数组
arr = np.arange(12).reshape(2, 3, 2)
print(np.tile(arr, 2)) # shape为(2, 3, 4)
print(np.repeat(arr, 2, axis=1)) # shape为(2, 6, 2)

[[[ 0  1  0  1]
  [ 2  3  2  3]
  [ 4  5  4  5]]

 [[ 6  7  6  7]
  [ 8  9  8  9]
  [10 11 10 11]]]
[[[ 0  1]
  [ 0  1]
  [ 2  3]
  [ 2  3]
  [ 4  5]
  [ 4  5]]

 [[ 6  7]
  [ 6  7]
  [ 8  9]
  [ 8  9]
  [10 11]
  [10 11]]]


## 增加和删除元素

In [22]:
# delete(a, indices [, axis])
# indices - 在维度axis上需要删除的序号，序号列表或slice语法
# axis - 维度序号，默认值为None，表示将a变为一维向量后进行删除
# 将数组a在axis维度上删除某些维度向量，返回一个新的数组
arr = np.arange(12).reshape(2, 3, 2)
print(np.delete(arr, 0, axis=1))
print(np.delete(arr, np.s_[:3], axis=1))
print(np.delete(arr, [1,3,5]))

[[[ 2  3]
  [ 4  5]]

 [[ 8  9]
  [10 11]]]
[]
[ 0  2  4  6  7  8  9 10 11]


In [23]:
# insert(a, indices, values [, axis])
# append(a, values [, axis])
# values - 增加的值向量或标量（广播方式）
# insert在数组a的axis维度上indices前插入值，append在数组的axis维度末尾增加值，值由values指定
arr = np.array([[1,2],[3,4]])
print(np.insert(arr, 1, 0, axis=1))
arr = np.arange(12).reshape(2, 3, 2)
print(np.insert(arr, 1, [[10, 11, 12], [13, 14, 15]], axis=2))
print(np.append(arr, np.arange(10, 16).reshape(2,3,1) , axis=2))

[[1 0 2]
 [3 0 4]]
[[[ 0 10  1]
  [ 2 11  3]
  [ 4 12  5]]

 [[ 6 13  7]
  [ 8 14  9]
  [10 15 11]]]
[[[ 0  1 10]
  [ 2  3 11]
  [ 4  5 12]]

 [[ 6  7 13]
  [ 8  9 14]
  [10 11 15]]]


In [24]:
# resize(arr, shape)
# ndarray.resize(shape)
# 将arr数组改成新的形状shape，如果shape比现在arr的形状大，resize会重复arr的数据进行填充，ndarray.resize会填充0
# resize返回新的数组，ndarray.resize不返回值，直接修改参数数组
arr = np.array([[0,1,2],[3,4,5]])
print(np.resize(arr, (3, 5)))
arr.resize((3, 5))
print(arr)

[[0 1 2 3 4]
 [5 0 1 2 3]
 [4 5 0 1 2]]
[[0 1 2 3 4]
 [5 0 0 0 0]
 [0 0 0 0 0]]


In [25]:
# trim_zeros(arr [, trim])
# trim - 'fb': 去除一维数组的前导和后导0值；'f': 去除前导0；'b': 去除后导0
# 去除一维数组的前导或后导0值
arr = np.array([0,0,0,1,2,3,0,0,1,0,0])
print(np.trim_zeros(arr))
print(np.trim_zeros(arr, trim='f'))

[1 2 3 0 0 1]
[1 2 3 0 0 1 0 0]


In [26]:
# unique(arr [, return_index, return_inverse, return_counts, axis])
# return_index - False（默认值）: 不返回arr中第一个出现唯一值的序号
# return_inverse - False（默认值）: 不返回可用于重构arr数组的序号
# return_count - False（默认值）: 不返回唯一值的个数
# axis - 求唯一值的维度，None（默认值）: 先将数组arr扁平化成一维数组再求唯一值
# 获得数组中的唯一值，返回值包括唯一值数组、第一次出现的序号数组、用于重构数组的序号数组和唯一值个数
np.random.seed(100)
arr = np.random.randint(0, 2, (2, 5))
print(arr)
print(np.unique(arr, axis=1))
arr = np.random.randint(0, 5, (3, 5))
print(arr)
uniqs, indices, inverses, count = np.unique(arr, return_index=True, return_inverse=True, return_counts=True)
print(uniqs)
print(indices)
print(inverses)
print(count)
print(uniqs[inverses].reshape(arr.shape)) # 重构原数组

[[0 0 1 1 1]
 [1 0 0 0 0]]
[[0 0 1]
 [0 1 0]]
[[2 2 2 2 1]
 [0 0 4 3 4]
 [2 0 3 1 2]]
[0 1 2 3 4]
[5 4 0 8 7]
[2 2 2 2 1 0 0 4 3 4 2 0 3 1 2]
[3 2 6 2 2]
[[2 2 2 2 1]
 [0 0 4 3 4]
 [2 0 3 1 2]]


## 重新排列元素

In [27]:
# flip(arr, axis)
# 将数组沿axis维度倒序输出，得到一个新的数组
arr = np.arange(12).reshape(2, 3, 2)
print(arr)
print(np.flip(arr, 1))
print(arr[:,::-1,:]) # 使用slicing语法获得相同效果

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 4  5]
  [ 2  3]
  [ 0  1]]

 [[10 11]
  [ 8  9]
  [ 6  7]]]
[[[ 4  5]
  [ 2  3]
  [ 0  1]]

 [[10 11]
  [ 8  9]
  [ 6  7]]]


In [28]:
# fliplr(arr)
# flipud(arr)
# 将一个二维矩阵的行（fliplr）或列（flipud）的顺序倒序，返回一个新数组
arr = np.random.randint(0, 5, (3, 3))
print(arr)
print(np.fliplr(arr))
print(arr[:,::-1]) # 使用slicing语法实现fliplr
print(np.flipud(arr))
print(arr[::-1,:]) # 使用slicing语法实现flipud

[[3 4 4]
 [1 3 4]
 [4 3 3]]
[[4 4 3]
 [4 3 1]
 [3 3 4]]
[[4 4 3]
 [4 3 1]
 [3 3 4]]
[[4 3 3]
 [1 3 4]
 [3 4 4]]
[[4 3 3]
 [1 3 4]
 [3 4 4]]


In [29]:
# reshape(arr, shape [, order])
# ndarray.reshape(shape [, order])
# 将数组转换为新的形状shape，新的形状必须与旧的形状元素个数一致
arr = np.arange(12)
print(np.reshape(arr, (2,3,2)))
print(np.reshape(arr, (-1,2,3))) # 使用-1做某个维度的参数

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [30]:
# roll(arr, shift [, axis])
# shift - 滚动的次数
# axis - None（默认值）: 将数组扁平化后再进行roll操作，然后变回数组的原始形状
# 循环滚动数组中沿axis方向的元素
arr = np.arange(12).reshape(2, 3, 2)
print(arr)
print(np.roll(arr, 2))
print(np.roll(arr, 1, axis=2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[10 11]
  [ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]
  [ 8  9]]]
[[[ 1  0]
  [ 3  2]
  [ 5  4]]

 [[ 7  6]
  [ 9  8]
  [11 10]]]


In [33]:
# rot90(arr [, k, axes])
# k - 转动次数
# axes - 定义转动平面的维度数组，默认值(0, 1)
# 将二维或以上数组沿axes定义的平面转动90度，转动方向从第一个维度到第二个维度
arr = np.arange(6).reshape(2, 3)
print(arr)
print(np.rot90(arr, k=1))
print(np.rot90(arr, k=-1))
arr = np.arange(12).reshape(2, 3, 2)
print(arr)
print(np.rot90(arr, 1, axes=(1,2)))
print(np.rot90(arr, 2, axes=(0,2)))

[[0 1 2]
 [3 4 5]]
[[2 5]
 [1 4]
 [0 3]]
[[3 0]
 [4 1]
 [5 2]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[[[ 1  3  5]
  [ 0  2  4]]

 [[ 7  9 11]
  [ 6  8 10]]]
[[[ 7  6]
  [ 9  8]
  [11 10]]

 [[ 1  0]
  [ 3  2]
  [ 5  4]]]
